---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: trello-controller
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./config/default
  prune: true
  sourceRef:
    kind: OCIRepository
    name: trello-controller
  timeout: 2m0s
  wait: true
  patches:
  - patch: |-
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: not-used
      rules:
      - apiGroups:
        - kustomize.toolkit.fluxcd.io
        resources:
        - kustomizations
        verbs:
        - get
        - list
        - patch
        - watch
    target:
      kind: ClusterRole
      name: manager-role
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: manager
                args:
                - "--target-api-version=kustomize.toolkit.fluxcd.io/v1beta2"
                - "--target-kind=Kustomization"
    target:
      kind: Deployment
      name: controller-manager
      namespace: system
